<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Banking Operations App\Banking Operations App.csproj" />
    <ProjectReference Include="..\BIZ\BIZ.csproj" />
    <ProjectReference Include="..\DAL\DAL.csproj" />
  </ItemGroup>

</Project>
